### ISSUE TITLE
老哥，在最新的macos 12.3版本 python2失效了

### ISSUE THREAD

**Issue by wisinfun** [xiaotu9639/alfred-yuque-workflow#4]
还能补救吗

**Comment by zzhanghub** [comment]
同样的问题，很困扰

**Comment by xiaotu9639** [comment]
> 还能补救吗

安装个python2（可以用miniconda安装），在alfred workflow页面编辑节点，里面调用python的地方改为 python2 的路径就可以了

**Comment by xiaotu9639** [comment]
已发布2.0.0版本，适配python3，在macos 13.1下使用正常
